name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti sesuai dengan cabang utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Ganti dengan versi Node.js yang kamu gunakan

      - name: Install dependencies
        run: npm install

      - name: Install Tailwind CSS globally
        run: npm install -g tailwindcss

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./styles.css -o ./dist/styles.css --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }} # Menggunakan token yang telah disimpan
          publish_dir: ./dist
          publish_branch: gh-pages # Cabang untuk publikasi
